// typescript/apps/web/src/pages/apps/calculator/temperature/index.tsx
import { Layout } from '@web/layout';
import { cf, ck, fc, fk, kc, kf } from '@web/utils/temperature/temperature';
import { NextPage } from 'next';
import { ChangeEvent, useState } from 'react';

type TemperatureUnit = 'celsius' | 'fahrenheit' | 'kelvin';

const TemperaturePage: NextPage = () => {
  const [temperature, setTemperature] = useState<
    Record<TemperatureUnit, number>
  >({
    celsius: 1,
    fahrenheit: cf(1),
    kelvin: ck(1),
  });

  return (
    <Layout nav full>
      <div className='container mx-auto h-full'>
        <div className='h-full p-4 md:p-8'>
          <div className='flex h-full items-center justify-center'>
            <div className='join join-vertical w-full lg:join-horizontal'>
              <label className='input join-item input-bordered flex w-full items-center gap-2'>
                <input
                  type='number'
                  name='celsius'
                  placeholder='Celsius'
                  min={1}
                  value={temperature.celsius}
                  onChange={(event: ChangeEvent<HTMLInputElement>) => {
                    const newCelsius: number = parseFloat(event.target.value);
                    setTemperature({
                      celsius: newCelsius,
                      fahrenheit: cf(newCelsius),
                      kelvin: ck(newCelsius),
                    });
                  }}
                  className='grow'
                />
                <span className='truncate'>°C (Celsius)</span>
              </label>
              <label className='input join-item input-bordered flex w-full items-center gap-2'>
                <input
                  type='number'
                  name='fahrenheit'
                  placeholder='fahrenheit'
                  min={1}
                  value={temperature.fahrenheit}
                  onChange={(event: ChangeEvent<HTMLInputElement>) => {
                    const newFahrenheit: number = parseFloat(
                      event.target.value
                    );
                    setTemperature({
                      celsius: fc(newFahrenheit),
                      fahrenheit: newFahrenheit,
                      kelvin: fk(newFahrenheit),
                    });
                  }}
                  className='grow'
                />
                <span className='truncate'>°F (Fahrenheit)</span>
              </label>
              <label className='input join-item input-bordered flex w-full items-center gap-2'>
                <input
                  type='number'
                  name='kelvin'
                  placeholder='kelvin'
                  min={1}
                  value={temperature.kelvin}
                  onChange={(event: ChangeEvent<HTMLInputElement>) => {
                    const newKelvin: number = parseFloat(event.target.value);
                    setTemperature({
                      celsius: kc(newKelvin),
                      fahrenheit: kf(newKelvin),
                      kelvin: newKelvin,
                    });
                  }}
                  className='grow'
                />
                <span className='truncate'>°K (Kelvin)</span>
              </label>
            </div>
          </div>
        </div>
      </div>
    </Layout>
  );
};

export default TemperaturePage;

// packages/app/web/solidjs.com/src/components/pages/start/modals/calculators/ConverterModal/tabs/physical/Temperature.tsx
import { createSignal } from 'solid-js';

type TemperatureUnit = 'celsius' | 'fahrenheit' | 'kelvin';

const convertTemperature = (
  fromAmount: number,
  fromUnit: TemperatureUnit,
  toUnit: TemperatureUnit
): number => {
  let celsiusValue: number;

  if (fromUnit === 'celsius') {
    celsiusValue = fromAmount;
  } else if (fromUnit === 'fahrenheit') {
    celsiusValue = ((fromAmount - 32) * 5) / 9;
  } else if (fromUnit === 'kelvin') {
    celsiusValue = fromAmount - 273.15;
  } else {
    celsiusValue = fromAmount;
  }

  if (toUnit === 'celsius') {
    return parseFloat(celsiusValue.toFixed(2));
  } else if (toUnit === 'fahrenheit') {
    return parseFloat(((celsiusValue * 9) / 5 + 32).toFixed(2));
  } else if (toUnit === 'kelvin') {
    return parseFloat((celsiusValue + 273.15).toFixed(2));
  } else {
    return parseFloat(celsiusValue.toFixed(2));
  }
};

export const Temperature = () => {
  const [celsius, setCelsius] = createSignal(0);
  const [fahrenheit, setFahrenheit] = createSignal(32);
  const [kelvin, setKelvin] = createSignal(273.15);

  const handleChange = (value: string, type: TemperatureUnit) => {
    const newAmount = parseFloat(value);
    if (isNaN(newAmount)) {
      setCelsius(0);
      setFahrenheit(32);
      setKelvin(273.15);
      return;
    }
    setCelsius(convertTemperature(newAmount, type, 'celsius'));
    setFahrenheit(convertTemperature(newAmount, type, 'fahrenheit'));
    setKelvin(convertTemperature(newAmount, type, 'kelvin'));
  };

  return (
    <div class="card flex w-full max-w-md flex-col gap-y-2 divide-y divide-white/10">
      {[
        { type: 'celsius' as TemperatureUnit, value: celsius },
        { type: 'fahrenheit' as TemperatureUnit, value: fahrenheit },
        { type: 'kelvin' as TemperatureUnit, value: kelvin },
      ].map(({ type, value }) => {
        return (
          <div
            key={type}
            class="flex items-center justify-center gap-x-2 px-4 py-2">
            <span class="capitalize">{type}</span>
            <input
              type="text"
              id={type}
              placeholder={type}
              value={value()}
              class="grow text-right focus:outline-none"
              onChange={(event: Event) =>
                handleChange((event.target as HTMLInputElement).value, type)
              }
            />
          </div>
        );
      })}
    </div>
  );
};
