// packages/app/web/solidjs.com/src/components/organisms/mocks/Browser.tsx
import { JSX } from 'solid-js';

interface BrowserProps {
  url?: string;
  children?: JSX.Element;
  class?: string;
}

export const Browser = (props: BrowserProps) => (
  <div
    class={`mockup-browser border-base-300 bg-base-100 w-full border ${props.class || ''}`}>
    <div class="mockup-browser-toolbar">
      <div class="input">{props.url ?? 'https://daisyui.com'}</div>
    </div>
    <div class="border-base-300 grid border-t">{props.children}</div>
  </div>
);

// packages/app/hieudoanm/src/components/organisms/mocks/Browser.tsx
import { FC, ReactNode } from 'react';

interface BrowserProps {
  url?: string;
  children?: ReactNode;
  className?: string;
}

export const Browser: FC<BrowserProps> = ({
  url = 'https://daisyui.com',
  children,
  className = '',
}) => {
  return (
    <div
      className={`mockup-browser border-base-300 bg-base-100 w-full border ${className}`}>
      <div className="mockup-browser-toolbar">
        <div className="input">{url}</div>
      </div>
      <div className="border-base-300 grid border-t">{children}</div>
    </div>
  );
};
Browser.displayName = 'Browser';
