// packages/app/web/nextjs.org/src/components/organisms/mocks/Terminal.tsx
import { FC, ReactNode } from 'react';

interface TerminalLine {
  prefix?: string;
  text: string;
  highlight?: boolean;
}

interface TerminalProps {
  lines?: TerminalLine[];
  children?: ReactNode;
  className?: string;
}

export const Terminal: FC<TerminalProps> = ({
  lines,
  children,
  className = '',
}) => (
  <div className={`mockup-code w-full ${className}`}>
    {lines
      ? lines.map((line, i) => (
          <pre
            key={i}
            data-prefix={line.prefix ?? ''}
            className={line.highlight ? 'bg-warning text-warning-content' : ''}>
            <code>{line.text}</code>
          </pre>
        ))
      : children}
  </div>
);

// packages/app/web/solidjs.com/src/components/organisms/mocks/Terminal.tsx
import { JSX } from 'solid-js';

interface TerminalLine {
  prefix?: string;
  text: string;
  highlight?: boolean;
}

interface TerminalProps {
  lines?: TerminalLine[];
  children?: JSX.Element;
  class?: string;
}

export const Terminal = (props: TerminalProps) => (
  <div class={`mockup-code w-full ${props.class || ''}`}>
    {props.lines
      ? props.lines.map((line, i) => (
          <pre
            key={i}
            data-prefix={line.prefix ?? ''}
            class={line.highlight ? 'bg-warning text-warning-content' : ''}>
            <code>{line.text}</code>
          </pre>
        ))
      : props.children}
  </div>
);
