// packages/app/solidjs.com/src/components/pages/start/modals/tools/FigletModal.tsx
import { createSignal } from 'solid-js';
import { ModalWrapper } from '@hieudoanm.github.io/components/atoms/ModalWrapper';

type FigletFont = Record<string, string[]>;

const STANDARD: FigletFont = {
  ' ': ['   ', '   ', '   ', '   ', '   ', '   '],
  A: [' /\\ ', '/  \\', '/__\\', '/  \\', '/  \\', '    '],
  B: ['|\\ ', '| \\', '|__\\', '|  \\', '|__/', '    '],
  C: [' /‾', '/  ', '|   ', '\\  ', ' \\_ ', '    '],
  D: ['|\\ ', '| \\', '|  \\', '|  /', '|_/ ', '    '],
  E: ['|‾‾', '|_ ', '|   ', '|   ', '|__', '    '],
  F: ['|‾‾', '|_ ', '|   ', '|   ', '|   ', '    '],
  G: [' /‾', '/  ', '| __', '\\  |', ' \\_ ', '    '],
  H: ['|  |', '|  |', '|__|', '|  |', '|  |', '    '],
  I: ['|‾|', ' | ', ' | ', ' | ', '|_|', '    '],
  J: ['  |', '  |', '  |', '\\  |', ' \\_ ', '    '],
  K: ['|\\ ', '|/ ', '|< ', '|\\ ', '| \\', '    '],
  L: ['|   ', '|   ', '|   ', '|   ', '|__', '    '],
  M: ['|\\/|', '|  |', '|  |', '|  |', '|  |', '    '],
  N: ['|\\ |', '| \\|', '|  |', '|  |', '|  |', '    '],
  O: [' /‾\\ ', '/   \\', '|   |', '\\   /', ' \\_ / ', '    '],
  P: ['|\\ ', '| \\', '|__/', '|   ', '|   ', '    '],
  Q: [' /‾\\ ', '/   \\', '|  Q|', '\\ \\/', ' \\_ \\', '    '],
  R: ['|\\ ', '| \\', '|__/', '|\\ ', '| \\', '    '],
  S: [' /‾', '/   ', '\\‾\\ ', '   /', '\\_/ ', '    '],
  T: ['‾|‾', ' | ', ' | ', ' | ', ' | ', '    '],
  U: ['|  |', '|  |', '|  |', '|  |', ' \\_ ', '    '],
  V: ['\\  /', ' \\/ ', '\\  /', ' \\/ ', ' \\/  ', '    '],
  W: ['\\    /', ' \\  / ', '  \\/  ', ' /\\  /\\', '/  \\/  \\', '    '],
  X: ['\\  /', ' \\/ ', ' /\\ ', '/  \\', '\\  /', '    '],
  Y: ['\\  /', ' \\/ ', '  | ', '  | ', '  | ', '    '],
  Z: ['‾‾‾', '  /', ' /  ', '/   ', '___', '    '],
  '0': [' 0 ', '/ \\', '|  |', '\\ /', ' 0 ', '    '],
  '1': [' 1 ', '/1 ', ' | ', ' | ', '_|_', '    '],
  '2': [' ‾\\ ', '   |', ' _/ ', '/   ', '‾‾‾', '    '],
  '3': ['‾‾\\ ', '   |', ' ‾\\ ', '   |', '__/ ', '    '],
  '4': ['|  |', '|  |', '|__|', '   |', '   |', '    '],
  '5': ['|‾‾', '|_ ', '  \\', '   |', '_/ ', '    '],
  '6': [' /‾', '/   ', '|‾\\ ', '|  |', ' \\_ ', '    '],
  '7': ['‾‾|', '  |', ' /  ', '/   ', '/   ', '    '],
  '8': [' /\\ ', '(  )', ' )( ', '(  )', ' \\/ ', '    '],
  '9': [' /\\ ', '(  )', ' \\_|', '   |', ' \\_ ', '    '],
  '!': ['|', '|', '|', ' ', '•', '    '],
  '?': ['/‾\\ ', '   |', '  / ', '  / ', '  • ', '    '],
  '.': ['  ', '  ', '  ', '  ', ' •', '    '],
  ',': ['  ', '  ', '  ', ' ,', ',/ ', '    '],
  '-': ['   ', '‾‾‾', '   ', '   ', '   ', '    '],
  _: ['   ', '   ', '   ', '   ', '___', '    '],
  ':': [' •', '  ', ' •', '  ', '  ', '    '],
  '#': [' # # ', '#####', ' # # ', '#####', ' # # ', '    '],
  '@': [' /‾\\ ', '/ @@ ', '| @@ ', '\\ @  ', ' \\‾/ ', '    '],
  '&': [' /\\ ', '(  )', ' ) \\ ', '(  \\', ' )__\\', '    '],
  '*': [' * ', '***', ' * ', '   ', '   ', '    '],
  '+': ['  |  ', '  |  ', '‾‾|‾‾', '  |  ', '  |  ', '    '],
  '/': ['   /', '  / ', ' /  ', '/   ', '/   ', '    '],
  '\\': ['\\   ', ' \\  ', '  \\ ', '   \\', '   \\', '    '],
  '(': [' /', '/ ', '|  ', '\\ ', ' \\', '    '],
  ')': ['\\ ', ' \\', '  |', ' / ', '/ ', '    '],
  '[': ['|‾', '| ', '| ', '| ', '|_', '    '],
  ']': ['‾|', ' |', ' |', ' |', '_|', '    '],
  '{': [' /‾', '/  ', '|   ', '\\  ', ' \\_ ', '    '],
  '}': ['‾\\ ', '  \\', '   |', '  /', '_ /', '    '],
  '|': ['|', '|', '|', '|', '|', '  '],
  '^': ['/\\', '   ', '   ', '   ', '   ', '    '],
  '~': ['~‾~', '   ', '   ', '   ', '   ', '    '],
  '`': ['\\', ' \\', '  ', '  ', '  ', '    '],
  "'": ['|', '/ ', '  ', '  ', '  ', '    '],
  '"': ['| |', '|/ ', '   ', '   ', '   ', '    '],
  '<': [' /', '/ ', '\\ ', ' \\', '  ', '    '],
  '>': ['\\ ', ' \\', ' / ', '/ ', '  ', '    '],
  '=': ['   ', '‾‾‾', '   ', '___', '   ', '    '],
  '%': ['/|', '/ ', ' / ', '/  |', '  / |', '    '],
  $: ['/‾\\ ', '$   ', ' \\_ ', '   $', '\\_ /', '    '],
};

const BLOCK: FigletFont = {
  ' ': [
    '      ',
    '      ',
    '      ',
    '      ',
    '      ',
    '      ',
    '      ',
    '      ',
  ],
  A: [
    '  ___  ',
    ' / _ \\ ',
    '/ /_\\ \\',
    '|  _  |',
    '| | | |',
    '\\_| |_/',
    '       ',
  ],
  B: [
    '______  ',
    '| ___ \\ ',
    '| |_/ / ',
    '| ___ \\ ',
    '| |_/ / ',
    '\\____/  ',
    '        ',
  ],
  C: [
    ' _____ ',
    '/  __ \\',
    '| /  \\/',
    '| |    ',
    '| \\__/\\',
    '\\_____/',
    '        ',
  ],
  D: [
    '______  ',
    '|  _  \\ ',
    '| | | | ',
    '| | | | ',
    '| |/ /  ',
    '|___/   ',
    '        ',
  ],
  E: [
    '______',
    '|  ___|',
    '| |__  ',
    '|  __| ',
    '| |___ ',
    '\\____/ ',
    '       ',
  ],
  F: [
    '______',
    '|  ___|',
    '| |_   ',
    '|  _|  ',
    '| |    ',
    '\\_|    ',
    '       ',
  ],
  G: [
    ' _____ ',
    '/  __ \\',
    '| /  \\/',
    '| |    ',
    '| \\__/\\',
    '\\_____/',
    '        ',
  ],
  H: [
    ' _   _ ',
    '| | | |',
    '| |_| |',
    '|  _  |',
    '| | | |',
    '\\_| |_/',
    '        ',
  ],
  I: ['_____', '|_   |', '  | | ', '  | | ', ' _| |_', '|_____|', '       '],
  J: [
    '  ___ ',
    ' |_  |',
    '   | |',
    '   | |',
    '/\\__/ /',
    '\\____/ ',
    '       ',
  ],
  K: [
    ' _   __',
    '| | / /',
    '| |/ / ',
    '|    \\ ',
    '| |\\  \\',
    '\\_| \\_/',
    '       ',
  ],
  L: [
    '_     ',
    '| |    ',
    '| |    ',
    '| |    ',
    '| |____',
    '\\_____/',
    '       ',
  ],
  M: [
    '___  ___',
    '|  \\/  |',
    '| .  . |',
    '| |\\/| |',
    '| |  | |',
    '\\_|  |_/',
    '        ',
  ],
  N: [
    ' _   _ ',
    '| \\ | |',
    '|  \\| |',
    '| . ` |',
    '| |\\  |',
    '\\_| \\_/',
    '        ',
  ],
  O: [
    ' _____ ',
    '/  _  \\',
    '| | | |',
    '| | | |',
    '\\ \\_/ /',
    ' \\___/ ',
    '        ',
  ],
  P: [
    '______  ',
    '| ___ \\ ',
    '| |_/ / ',
    '|  __/  ',
    '| |     ',
    '\\_|     ',
    '        ',
  ],
  Q: [
    ' _____ ',
    '/  _  \\',
    '| | | |',
    '| | | |',
    '\\ \\/\\/ /',
    ' \\_/\\_/ ',
    '        ',
  ],
  R: [
    '______  ',
    '| ___ \\ ',
    '| |_/ / ',
    '|    /  ',
    '| |\\ \\  ',
    '\\_| \\_| ',
    '        ',
  ],
  S: [
    ' _____ ',
    '/  ___|',
    '\\ `--. ',
    ' `--. \\',
    '/\\__/ /',
    '\\____/ ',
    '       ',
  ],
  T: ['_____', '|_   |', '  | | ', '  | | ', '  | | ', '  \\_/ ', '       '],
  U: [
    ' _   _ ',
    '| | | |',
    '| | | |',
    '| | | |',
    '\\ \\_/ /',
    ' \\___/ ',
    '        ',
  ],
  V: [
    '__   __',
    '\\ \\ / /',
    ' \\ V / ',
    '  \\ /  ',
    '   V   ',
    '   \\_  ',
    '        ',
  ],
  W: [
    '__   __ ',
    '\\ \\ / / ',
    ' \\ V /  ',
    ' /   \\  ',
    '/ /^\\ \\ ',
    '\\/   \\/ ',
    '        ',
  ],
  X: [
    '__   __',
    '\\ \\ / /',
    ' \\ V / ',
    '  > <  ',
    ' / . \\ ',
    '/_/ \\_\\',
    '       ',
  ],
  Y: [
    '__   __',
    '\\ \\ / /',
    ' \\ V / ',
    '  \\ /  ',
    '   | |  ',
    '   \\_/ ',
    '        ',
  ],
  Z: [
    '_____',
    '\\__  |',
    '   / / ',
    '  / /  ',
    './ /___',
    '\\_____/',
    '       ',
  ],
  '0': [
    ' ___  ',
    '/ _ \\ ',
    '| | | |',
    '| | | |',
    '\\  __/ ',
    ' \\___/ ',
    '       ',
  ],
  '1': [' _ ', '/ |', '| |', '| |', '| |', '|_|', '   '],
  '2': ['___  ', '\\  \\ ', ' \\  \\', ' /  /', '/__/ ', '\\___/', '      '],
  '3': ['___  ', '\\  \\ ', ' \\__\\', ' ___\\', '\\___/', '     ', '      '],
  '4': ['   _  ', '  | | ', ' _| | ', '|_  | ', '  | | ', '  |_| ', '       '],
  '5': [' ___ ', '| __|', '|__ \\', ' ___\\', '|____/', '      ', '       '],
  '6': [' ___ ', '/ _ \\', '| (_)', '\\__, \\', '  (_/', '      ', '       '],
  '7': [
    '_____',
    '\\  __|',
    ' \\ \\ ',
    '  \\ \\',
    '   \\_\\',
    '      ',
    '       ',
  ],
  '8': [' ___ ', '/ _ \\', '| (_)|', '\\__, |', '  / / ', ' /_/  ', '       '],
  '9': [' ___ ', '/ _ \\', '| | |', '\\__,_|', '      ', '      ', '       '],
  '!': ['_', '|', '|', '|', '_', '.', ' '],
  '?': [' ___ ', '|__ \\', '  / /', ' |_| ', ' (_) ', '     ', '      '],
  '.': ['  ', '  ', '  ', '  ', '_ ', '(_)', '  '],
  '-': ['      ', '______', '      ', '      ', '      ', '      ', '      '],
  _: [
    '       ',
    '       ',
    '       ',
    '       ',
    '_______',
    '       ',
    '       ',
  ],
};

const SMALL: FigletFont = {
  ' ': ['  ', '  ', '  ', '  ', '  '],
  A: [' _ ', '/_\\', '/ _\\', '\\__/', '    '],
  B: ['|__ \\', ' / /', ' |_|', ' (_)', '     '],
  C: [' ___ ', '/ __|', '\\__ \\', '|___/', '     '],
  D: ['|  \\', '| ` \\', '| |) |', '|___/', '     '],
  E: ['|__ \\', ' / /', ' |_|', ' (_)', '     '],
  F: ['|__ \\', ' / /', ' |_|', ' (_)', '     '],
  G: [' ___ ', '/ __|', '\\__ \\', '|___/', '     '],
  H: ['| |_| |', "| '_  |", '|_| |_|', '       '],
  I: ['(_)', ' | ', ' |_', '    '],
  J: [' _ ', '| |', '| |', ' \\|', '   '],
  K: ['|__/|', '| \\  ', '|_|\\_ ', '      '],
  L: ['| |  ', '| |  ', '|___|', '     '],
  M: ['|  V  |', '| \\_/ |', '|_| |_|', '       '],
  N: ['|\\ |', '| \\|', '|_  ', '   '],
  O: [' ___ ', '/ _ \\', '\\___/', '     '],
  P: ['|__ \\', ' / /', ' |_|', ' (_)', '     '],
  Q: [' ___ ', '/ _ \\', '\\__,_\\', '     '],
  R: ['|__ \\', ' / /', ' |_|', ' (_)', '     '],
  S: [' ___', '/ __|', '\\__ \\', '|___/', '     '],
  T: ['_|_', ' | ', ' |_', '   '],
  U: ['| | | |', '| |_| |', '\\___/ ', '      '],
  V: ['\\  / ', ' \\/ ', '  \\  ', '     '],
  W: ['\\    /', ' \\/\\/ ', '  \\/  ', '      '],
  X: ['\\ \\/', ' ><', '/_/\\', '    '],
  Y: ['\\   /', ' \\_/ ', '  |  ', '     '],
  Z: ['___ ', '  _/', ' /_ ', '/___|', '     '],
  '0': [' ___ ', '/ _ \\', '\\___/', '     '],
  '1': [' _ ', '/ |', '|_|', '   '],
  '2': ['___ ', '|_  \\', ' / / ', '/___|', '     '],
  '3': ['___  ', '|_  )', ' / / ', '/___|', '     '],
  '4': ['_ _ ', '| | |', '|_  _|', '  |_| ', '      '],
  '5': ['___', '| __|', '|__ \\', '|___/', '     '],
  '6': [' ___ ', '/ __|', '\\__ \\', '|___/', '     '],
  '7': ['___ ', '  / /', ' / / ', '/_/  ', '     '],
  '8': [' ___ ', '/ _ \\', '\\___/', '     '],
  '9': [' ___ ', '/ _ \\', '\\__,_|', '      '],
  '!': ['_', '|', '!', '.', ' '],
  '?': ['___ ', '|__ \\', ' / /', '|_|  ', '(_)  ', '     '],
  '.': ['  ', '  ', ' _', '(_)', '  '],
  '-': ['    ', '____', '    ', '    ', '    '],
};

const BANNER: FigletFont = {
  ' ': ['     ', '     ', '     ', '     ', '     ', '     '],
  A: ['  #  ', ' # # ', '#####', '#   #', '#   #', '      '],
  B: ['#### ', '#   #', '#### ', '#   #', '#### ', '      '],
  C: [' ####', '#    ', '#    ', '#    ', ' ####', '      '],
  D: ['#### ', '#   #', '#   #', '#   #', '#### ', '      '],
  E: '#####\n#    \n###  \n#    \n#####\n      '.split('\n'),
  F: '#####\n#    \n###  \n#    \n#    \n      '.split('\n'),
  G: [' ####', '#    ', '# ###', '#   #', ' ####', '      '],
  H: ['#   #', '#   #', '#####', '#   #', '#   #', '      '],
  I: ['#####', '  #  ', '  #  ', '  #  ', '#####', '      '],
  J: ['  ###', '   # ', '   # ', '#  # ', ' ##  ', '      '],
  K: ['#  # ', '# #  ', '##   ', '# #  ', '#  # ', '      '],
  L: ['#    ', '#    ', '#    ', '#    ', '#####', '      '],
  M: ['#   #', '## ##', '# # #', '#   #', '#   #', '      '],
  N: ['#   #', '##  #', '# # #', '#  ##', '#   #', '      '],
  O: [' ### ', '#   #', '#   #', '#   #', ' ### ', '      '],
  P: ['#### ', '#   #', '#### ', '#    ', '#    ', '      '],
  Q: [' ### ', '#   #', '# # #', '#  # ', ' ## #', '      '],
  R: ['#### ', '#   #', '#### ', '# #  ', '#  # ', '      '],
  S: [' ####', '#    ', ' ### ', '    #', '#### ', '      '],
  T: ['#####', '  #  ', '  #  ', '  #  ', '  #  ', '      '],
  U: ['#   #', '#   #', '#   #', '#   #', ' ### ', '      '],
  V: ['#   #', '#   #', '#   #', ' # # ', '  #  ', '      '],
  W: ['#   #', '#   #', '# # #', '## ##', '#   #', '      '],
  X: ['#   #', ' # # ', '  #  ', ' # # ', '#   #', '      '],
  Y: ['#   #', ' # # ', '  #  ', '  #  ', '  #  ', '      '],
  Z: ['#####', '   # ', '  #  ', ' #   ', '#####', '      '],
  '0': [' ### ', '#  ##', '# # #', '##  #', ' ### ', '      '],
  '1': ['  #  ', ' ##  ', '  #  ', '  #  ', '#####', '      '],
  '2': [' ### ', '#   #', '  ## ', ' #   ', '#####', '      '],
  '3': ['#### ', '    #', ' ### ', '    #', '#### ', '      '],
  '4': ['#  # ', '#  # ', '#####', '   # ', '   # ', '      '],
  '5': ['#####', '#    ', '#### ', '    #', '#### ', '      '],
  '6': [' ### ', '#    ', '#### ', '#   #', ' ### ', '      '],
  '7': ['#####', '   # ', '  #  ', ' #   ', '#    ', '      '],
  '8': [' ### ', '#   #', ' ### ', '#   #', ' ### ', '      '],
  '9': [' ### ', '#   #', ' ####', '    #', ' ### ', '      '],
  '!': ['  #  ', '  #  ', '  #  ', '     ', '  #  ', '      '],
  '?': [' ### ', '#   #', '  ## ', '     ', '  #  ', '      '],
  '.': ['     ', '     ', '     ', '  #  ', '  #  ', '      '],
  '-': ['     ', '     ', '#####', '     ', '     ', '      '],
};

const FONTS: Record<string, FigletFont> = {
  Standard: STANDARD,
  Block: BLOCK,
  Small: SMALL,
  Banner: BANNER,
};

const renderFiglet = (text: string, fontName: string): string => {
  const font = FONTS[fontName] ?? FONTS.Standard;
  const chars = text.toUpperCase().split('');
  const fallback = font[' '] ?? ['   ', '   ', '   ', '   ', '   '];
  const rows = fallback.length;

  const lines: string[] = Array(rows).fill('');
  for (const ch of chars) {
    const glyph = font[ch] ?? font['?'] ?? fallback;
    const h = glyph.length;
    for (let r = 0; r < rows; r++) {
      lines[r] += r < h ? glyph[r] : ' '.repeat((glyph[0] ?? '').length);
    }
  }
  return lines.join('\n');
};

const FONT_NAMES = Object.keys(FONTS);

export const FigletModal = (props: { onClose: () => void }) => {
  const [text, setText] = createSignal('Hello, World!');
  const [font, setFont] = createSignal('Standard');
  const [copied, setCopied] = createSignal(false);

  const output = () => renderFiglet(text() || 'Hello, World!', font());

  const copy = async () => {
    await navigator.clipboard.writeText(output());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const onKeyDown = (e: KeyboardEvent) => {
    if (e.key === 'Escape') props.onClose();
  };

  return (
    <ModalWrapper
      onClose={props.onClose}
      title="FIGlet Generator"
      size="max-w-2xl">
      <div onKeyDown={onKeyDown}>
        {/* Input */}
        <div class="mb-3 flex gap-2">
          <input
            autoFocus
            type="text"
            value={text()}
            onChange={(e: Event) =>
              setText((e.target as HTMLInputElement).value)
            }
            placeholder="Type something…"
            maxLength={20}
            class="input input-bordered flex-1 font-mono"
          />
          <select
            value={font()}
            onChange={(e: Event) =>
              setFont((e.target as HTMLSelectElement).value)
            }
            class="select select-bordered">
            {FONT_NAMES.map((f) => (
              <option key={f} value={f}>
                {f}
              </option>
            ))}
          </select>
        </div>

        {/* Font tabs */}
        <div role="tablist" class="tabs tabs-boxed mb-4">
          {FONT_NAMES.map((f) => (
            <a
              key={f}
              role="tab"
              class={`tab ${font() === f ? 'tab-active' : ''}`}
              onClick={() => setFont(f)}>
              {f}
            </a>
          ))}
        </div>

        {/* Output */}
        <div class="bg-base-200 mb-3 overflow-x-auto rounded-xl p-4">
          <pre class="text-base-content/80 font-mono text-xs leading-tight whitespace-pre">
            {output()}
          </pre>
        </div>

        {/* Character count + hint */}
        <div class="mb-3 flex items-center justify-between text-xs opacity-40">
          <span>
            {text().length}/20 chars · letters, digits, punctuation supported
          </span>
          <span>Rendered in {font()}</span>
        </div>

        {/* Actions */}
        <div class="flex gap-2">
          <button
            class={`btn btn-sm flex-1 ${copied() ? 'btn-success' : 'btn-primary'}`}
            onClick={copy}>
            {copied() ? '✓ Copied' : '📋 Copy ASCII'}
          </button>
          <button class="btn btn-ghost btn-sm" onClick={() => setText('')}>
            Clear
          </button>
        </div>
      </div>
    </ModalWrapper>
  );
};

// packages/app/web/nextjs.org/src/components/pages/start/modals/tools/FigletModal/index.tsx
import { ModalWrapper } from '@hieudoanm.github.io/components/atoms/ModalWrapper';
import { FC, useState } from 'react';

import { FONT_NAMES, renderFiglet } from './utils/render';

export const FigletModal: FC<{ onClose: () => void }> = ({ onClose }) => {
  const [text, setText] = useState('Hello, World!');
  const [font, setFont] = useState('Standard');
  const [copied, setCopied] = useState(false);

  const output = renderFiglet(text || 'Hello, World!', font);

  const copy = async () => {
    await navigator.clipboard.writeText(output);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const onKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Escape') onClose();
  };

  return (
    <ModalWrapper onClose={onClose} title="FIGlet Generator" size="max-w-2xl">
      <div onKeyDown={onKeyDown}>
        <div className="mb-3 flex gap-2">
          <input
            autoFocus
            type="text"
            value={text}
            onChange={(e) => setText(e.target.value)}
            placeholder="Type something…"
            maxLength={20}
            className="input input-bordered flex-1 font-mono"
          />
          <select
            value={font}
            onChange={(e) => setFont(e.target.value)}
            className="select select-bordered">
            {FONT_NAMES.map((f) => (
              <option key={f} value={f}>
                {f}
              </option>
            ))}
          </select>
        </div>

        <div role="tablist" className="tabs tabs-boxed mb-4">
          {FONT_NAMES.map((f) => (
            <a
              key={f}
              role="tab"
              className={`tab ${font === f ? 'tab-active' : ''}`}
              onClick={() => setFont(f)}>
              {f}
            </a>
          ))}
        </div>

        <div className="bg-base-200 mb-3 overflow-x-auto rounded-xl p-4">
          <pre className="text-base-content/80 font-mono text-xs leading-tight whitespace-pre">
            {output}
          </pre>
        </div>

        <div className="mb-3 flex items-center justify-between text-xs opacity-40">
          <span>
            {text.length}/20 chars · letters, digits, punctuation supported
          </span>
          <span>Rendered in {font}</span>
        </div>

        <div className="flex gap-2">
          <button
            className={`btn btn-sm flex-1 ${copied ? 'btn-success' : 'btn-primary'}`}
            onClick={copy}>
            {copied ? '✓ Copied' : '📋 Copy ASCII'}
          </button>
          <button className="btn btn-ghost btn-sm" onClick={() => setText('')}>
            Clear
          </button>
        </div>
      </div>
    </ModalWrapper>
  );
};
