// packages/app/hieudoanm/web/solidjs.com/src/components/atoms/ModalWrapper.tsx
import { JSX } from 'solid-js';

type ModalWrapperProps = {
  children: JSX.Element;
  onClose: () => void;
};

export const ModalWrapper = (props: ModalWrapperProps) => {
  return (
    <div class="fixed inset-0 z-50 flex items-center justify-center">
      <div class="fixed inset-0 bg-black/50" onClick={props.onClose} />
      <div class="bg-base-100 relative z-10 max-h-[90vh] w-full max-w-4xl overflow-y-auto rounded-2xl shadow-2xl">
        <button
          onClick={props.onClose}
          class="btn btn-ghost btn-sm btn-square absolute top-2 right-2 z-20">
          ✕
        </button>
        {props.children}
      </div>
    </div>
  );
};

// packages/app/hieudoanm/web/nextjs.org/src/components/atoms/ModalWrapper.tsx
import { FC, ReactNode } from 'react';

interface ModalWrapperProps {
  onClose: () => void;
  title: string;
  subtitle?: string;
  footerNote?: string;
  size?: string;
  fullHeight?: boolean;
  children: ReactNode;
}

export const ModalWrapper: FC<ModalWrapperProps> = ({
  onClose,
  title,
  subtitle,
  footerNote,
  size = 'max-w-sm',
  fullHeight = false,
  children,
}) => {
  if (fullHeight) {
    return (
      <dialog
        open
        className="modal modal-open"
        style={{ background: 'rgba(0,0,0,0.6)', backdropFilter: 'blur(4px)' }}>
        <div
          className={`modal-box border-base-content/15 flex h-[90vh] w-full ${size} flex-col overflow-hidden border p-0`}>
          <div className="border-base-300 flex items-center justify-between border-b px-4 py-3">
            <h3 className="text-sm font-bold">{title}</h3>
            <button
              onClick={onClose}
              className="btn btn-sm btn-circle btn-ghost opacity-60 hover:opacity-100">
              ✕
            </button>
          </div>
          {children}
        </div>
        <div className="modal-backdrop" onClick={onClose} />
      </dialog>
    );
  }

  return (
    <dialog
      open
      className="modal modal-open"
      style={{ background: 'rgba(0,0,0,0.6)', backdropFilter: 'blur(4px)' }}>
      <div
        className={`card bg-base-100 border-base-300 w-full ${size} border shadow-2xl`}>
        <div className="card-body gap-5 p-6">
          <div className="flex items-start justify-between">
            <div>
              <h2 className="text-lg font-black tracking-tight">{title}</h2>
              {subtitle && (
                <p className="text-base-content/40 mt-0.5 font-mono text-[10px] tracking-widest uppercase">
                  {subtitle}
                </p>
              )}
            </div>
            <button
              onClick={onClose}
              className="btn btn-ghost btn-xs btn-square text-base opacity-60 hover:opacity-100">
              ✕
            </button>
          </div>
          {children}
          {footerNote && (
            <p className="text-base-content/20 text-center font-mono text-[10px] tracking-widest uppercase">
              {footerNote}
            </p>
          )}
        </div>
      </div>
      <form method="dialog" className="modal-backdrop">
        <button onClick={onClose}>close</button>
      </form>
    </dialog>
  );
};

ModalWrapper.displayName = 'ModalWrapper';
