// packages/app/web/solidjs.com/src/components/organisms/mocks/Phone.tsx
import { JSX } from 'solid-js';

interface PhoneProps {
  children?: JSX.Element;
  class?: string;
}

export const Phone = (props: PhoneProps) => (
  <div class={`mockup-phone border-gray-400 ${props.class || ''}`}>
    <div class="mockup-phone-camera" />
    <div class="mockup-phone-display bg-neutral-900 text-white">
      {props.children}
    </div>
  </div>
);

// packages/app/web/nextjs.org/src/components/organisms/mocks/Phone.tsx
import { FC, ReactNode } from 'react';

interface PhoneProps {
  children?: ReactNode;
  className?: string;
}

export const Phone: FC<PhoneProps> = ({ children, className = '' }) => {
  return (
    <div className={`mockup-phone border-gray-400 ${className}`}>
      <div className="mockup-phone-camera" />
      <div className="mockup-phone-display bg-neutral-900 text-white">
        {children}
      </div>
    </div>
  );
};
Phone.displayName = 'Phone';
