// packages/app/solid.js/src/components/organisms/mocks/Window.tsx
import { JSX } from 'solid-js';

interface WindowProps {
  children?: JSX.Element;
  class?: string;
}

export const Window = (props: WindowProps) => (
  <div
    class={`mockup-window border-base-300 bg-base-100 w-full border ${props.class || ''}`}>
    <div class="border-base-300 border-t">{props.children}</div>
  </div>
);

// packages/app/web/nextjs.org/src/components/organisms/mocks/Window.tsx
import { FC, ReactNode } from 'react';

interface WindowProps {
  children?: ReactNode;
  className?: string;
}

export const Window: FC<WindowProps> = ({ children, className = '' }) => (
  <div
    className={`mockup-window border-base-300 bg-base-100 w-full border ${className}`}>
    <div className="border-base-300 border-t">{children}</div>
  </div>
);
