// packages/app/solidjs.com/src/components/pages/start/modals/calculators/ConverterModal/tabs/math/Roman.tsx
import { createSignal } from 'solid-js';
import { arabic2roman, roman2arabic } from '@hieudoanm/number';

const INITIAL_NUMBER = 10;

export const Roman = () => {
  const [arabicNumber, setArabicNumber] = createSignal(
    INITIAL_NUMBER.toString()
  );
  const [romanNumber, setRomanNumber] = createSignal(
    arabic2roman(INITIAL_NUMBER)
  );

  const handleChange = (value: string, type: string) => {
    const newArabicNumber = type === 'arabic' ? value : roman2arabic(value);
    const newRomanNumber =
      type === 'roman' ? value : arabic2roman(parseInt(value, 10));
    setArabicNumber(newArabicNumber);
    setRomanNumber(newRomanNumber);
  };

  return (
    <div class="card flex w-full max-w-sm flex-col gap-y-2 divide-y divide-white/10">
      {[
        { type: 'arabic', value: arabicNumber },
        { type: 'roman', value: romanNumber },
      ].map(({ type, value }) => {
        return (
          <div
            key={type}
            class="flex items-center justify-center gap-x-2 px-4 py-2">
            <span class="capitalize">{type}</span>
            <input
              type="text"
              id={type}
              placeholder={type}
              value={value()}
              onChange={(event: Event) =>
                handleChange((event.target as HTMLInputElement).value, type)
              }
              class="grow text-right focus:outline-none"
            />
          </div>
        );
      })}
    </div>
  );
};

// packages/app/nextjs.org/src/components/pages/start/modals/calculators/ConverterModal/tabs/math/Roman.tsx
import { arabic2roman, roman2arabic } from '@hieudoanm/number';
import { FC, useState } from 'react';

const INITIAL_NUMBER: number = 10;

export const Roman: FC = () => {
  const [
    {
      arabicNumber = INITIAL_NUMBER.toString(),
      romanNumber = arabic2roman(INITIAL_NUMBER),
    },
    setState,
  ] = useState<{
    arabicNumber: string;
    romanNumber: string;
  }>({
    arabicNumber: INITIAL_NUMBER.toString(),
    romanNumber: arabic2roman(INITIAL_NUMBER),
  });

  return (
    <div className="card flex w-full max-w-sm flex-col gap-y-2 divide-y divide-white/10">
      {[
        { type: 'arabic', value: arabicNumber },
        { type: 'roman', value: romanNumber },
      ].map(({ type, value }) => {
        return (
          <div
            key={type}
            className="flex items-center justify-center gap-x-2 px-4 py-2">
            <span className="capitalize">{type}</span>
            <input
              type="text"
              id={type}
              placeholder={type}
              value={value}
              onChange={(event) => {
                const newValue = event.target.value;
                const newArabicNumber: string =
                  type === 'arabic' ? newValue : roman2arabic(newValue);
                const newRomanNumber: string =
                  type === 'roman'
                    ? newValue
                    : arabic2roman(parseInt(newValue, 10));
                setState((previous) => ({
                  ...previous,
                  arabicNumber: newArabicNumber,
                  romanNumber: newRomanNumber,
                }));
              }}
              className="grow text-right focus:outline-none"
            />
          </div>
        );
      })}
    </div>
  );
};
