// web/src/pages/apps/calculator/length/index.tsx
import { Layout } from '@web/layout';
import { ChangeEvent, useState } from 'react';

type Length = 'yard' | 'foot' | 'inch' | 'cm' | 'm' | 'km';

const lengthRates: Record<Length, number> = {
  yard: 1,
  foot: 3,
  inch: 36,
  cm: 91.44,
  m: 0.9144,
  km: 0.0009144,
};

const convert =
  (rates: Record<string, number>) =>
  (from: string, anount: number): Record<string, number> => {
    const tos: string[] = Object.keys(rates);
    const result: Record<string, number> = {} as Record<string, number>;
    for (const to of tos) {
      result[to] = parseFloat(((anount * rates[to]) / rates[from]).toFixed(2));
    }
    return result;
  };

const convertLength = convert(lengthRates);

const ConverterPage = () => {
  const [length, setLength] = useState<Record<Length, number>>(lengthRates);

  return (
    <Layout nav full>
      <div className='container mx-auto h-full'>
        <div className='h-full p-4 md:p-8'>
          <div className='flex h-full items-center justify-center'>
            <div className='flex flex-col gap-y-4 md:gap-y-8'>
              <div className='flex flex-col gap-y-4'>
                <span className='capitalize'>imperial</span>
                <div className='join join-vertical w-full lg:join-horizontal'>
                  <label className='input join-item input-bordered flex w-full items-center gap-2'>
                    <input
                      type='number'
                      name='yard'
                      placeholder='yard'
                      min={0}
                      value={length.yard}
                      onChange={(event: ChangeEvent<HTMLInputElement>) => {
                        const newYard: number = parseFloat(event.target.value);
                        setLength(convertLength('yard', newYard));
                      }}
                      className='grow'
                    />
                    <span>yard</span>
                  </label>
                  <label className='input join-item input-bordered flex w-full items-center gap-2'>
                    <input
                      type='number'
                      name='foot'
                      placeholder='foot'
                      min={0}
                      value={length.foot}
                      onChange={(event: ChangeEvent<HTMLInputElement>) => {
                        const newFoot: number = parseFloat(event.target.value);
                        setLength(convertLength('foot', newFoot));
                      }}
                      className='grow'
                    />
                    <span>foot</span>
                  </label>
                  <label className='input join-item input-bordered flex w-full items-center gap-2'>
                    <input
                      type='number'
                      name='inch'
                      placeholder='inch'
                      min={0}
                      value={length.inch}
                      onChange={(event: ChangeEvent<HTMLInputElement>) => {
                        const newInch: number = parseFloat(event.target.value);
                        setLength(convertLength('inch', newInch));
                      }}
                      className='grow'
                    />
                    <span>inch</span>
                  </label>
                </div>
              </div>
              <div className='flex flex-col gap-y-4'>
                <span className='capitalize'>metric</span>
                <div className='join join-vertical w-full lg:join-horizontal'>
                  <label className='input join-item input-bordered flex w-full items-center gap-2'>
                    <input
                      type='number'
                      name='cm'
                      placeholder='cm'
                      min={0}
                      value={length.cm}
                      onChange={(event: ChangeEvent<HTMLInputElement>) => {
                        const newCm: number = parseFloat(event.target.value);
                        setLength(convertLength('cm', newCm));
                      }}
                      className='grow'
                    />
                    <span>cm</span>
                  </label>
                  <label className='input join-item input-bordered flex w-full items-center gap-2'>
                    <input
                      type='number'
                      name='m'
                      placeholder='m'
                      min={0}
                      value={length.m}
                      onChange={(event: ChangeEvent<HTMLInputElement>) => {
                        const newM: number = parseFloat(event.target.value);
                        setLength(convertLength('m', newM));
                      }}
                      className='grow'
                    />
                    <span>m</span>
                  </label>
                  <label className='input join-item input-bordered flex w-full items-center gap-2'>
                    <input
                      type='number'
                      name='km'
                      placeholder='km'
                      min={0}
                      value={length.km}
                      onChange={(event: ChangeEvent<HTMLInputElement>) => {
                        const newKm: number = parseFloat(event.target.value);
                        setLength(convertLength('km', newKm));
                      }}
                      className='grow'
                    />
                    <span>km</span>
                  </label>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </Layout>
  );
};

export default ConverterPage;

// packages/app/solidjs.com/src/components/pages/start/modals/calculators/ConverterModal/tabs/physical/Length.tsx
import { createSignal } from 'solid-js';

type Length = 'yard' | 'foot' | 'inch' | 'centimeter' | 'meter' | 'kilometer';

const lengthRates: Record<Length, number> = {
  yard: 1,
  foot: 3,
  inch: 36,
  centimeter: 91.44,
  meter: 0.9144,
  kilometer: 0.0009144,
};

const convertRates =
  (lengthRates: Record<string, number> = {}) =>
  (
    {
      fromAmount,
      fromUnit,
      toUnit,
    }: {
      fromAmount: number;
      fromUnit: string;
      toUnit: string;
    } = { fromAmount: 1, fromUnit: 'inch', toUnit: 'cm' }
  ): number => {
    return parseFloat(
      ((fromAmount * lengthRates[toUnit]) / lengthRates[fromUnit]).toFixed(2)
    );
  };

export const Length = () => {
  const [yard, setYard] = createSignal(lengthRates.yard);
  const [foot, setFoot] = createSignal(lengthRates.foot);
  const [inch, setInch] = createSignal(lengthRates.inch);
  const [centimeter, setCentimeter] = createSignal(lengthRates.centimeter);
  const [meter, setMeter] = createSignal(lengthRates.meter);
  const [kilometer, setKilometer] = createSignal(lengthRates.kilometer);

  const handleChange = (value: string, type: string) => {
    const newAmount = parseFloat(value) || 0;
    setYard(
      type === 'yard'
        ? newAmount
        : convertRates(lengthRates)({
            fromAmount: newAmount,
            fromUnit: type,
            toUnit: 'yard',
          })
    );
    setFoot(
      type === 'foot'
        ? newAmount
        : convertRates(lengthRates)({
            fromAmount: newAmount,
            fromUnit: type,
            toUnit: 'foot',
          })
    );
    setInch(
      type === 'inch'
        ? newAmount
        : convertRates(lengthRates)({
            fromAmount: newAmount,
            fromUnit: type,
            toUnit: 'inch',
          })
    );
    setKilometer(
      type === 'kilometer'
        ? newAmount
        : convertRates(lengthRates)({
            fromAmount: newAmount,
            fromUnit: type,
            toUnit: 'kilometer',
          })
    );
    setMeter(
      type === 'meter'
        ? newAmount
        : convertRates(lengthRates)({
            fromAmount: newAmount,
            fromUnit: type,
            toUnit: 'meter',
          })
    );
    setCentimeter(
      type === 'centimeter'
        ? newAmount
        : convertRates(lengthRates)({
            fromAmount: newAmount,
            fromUnit: type,
            toUnit: 'centimeter',
          })
    );
  };

  return (
    <div class="card flex w-full max-w-md flex-col gap-y-2 divide-y divide-white/10">
      {[
        { type: 'yard', value: yard },
        { type: 'foot', value: foot },
        { type: 'inch', value: inch },
        { type: 'centimeter', value: centimeter },
        { type: 'meter', value: meter },
        { type: 'kilometer', value: kilometer },
      ].map(({ type, value }) => {
        return (
          <div
            key={type}
            class="flex items-center justify-center gap-x-2 px-4 py-2">
            <span class="capitalize">{type}</span>
            <input
              type="text"
              id={type}
              placeholder={type}
              value={value()}
              onChange={(event: Event) =>
                handleChange((event.target as HTMLInputElement).value, type)
              }
              class="grow text-right focus:outline-none"
            />
          </div>
        );
      })}
    </div>
  );
};
